version: '3'
services:
  api:
    image: node:16.16.0
    container_name: api
    working_dir: /app
    command: npm start
    ports:
      - "5000:5000"
    volumes:
      - "./server/:/app"
  web:
    image: node:16.16.0
    container_name: web
    working_dir: /client
    command: npm start
    ports:
      - "3000:3000"
    volumes:
      - "./client/:/client"   



